# Generated by Django 6.0.3 on 2026-03-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('goles_local', models.PositiveIntegerField(blank=True, null=True)),
                ('goles_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('sin_comenzar', 'Sin comenzar'), ('finalizado', 'Finalizado')], default='sin_comenzar', max_length=20)),
                ('resultado', models.CharField(blank=True, choices=[('local', 'Victoria local'), ('visitante', 'Victoria visitante'), ('empate', 'Empate'), ('penales_local', 'Penales local'), ('penales_visitante', 'Penales visitante')], max_length=20, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='partidos.jornada')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='equipos.equipo')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='equipos.equipo')),
            ],
            options={
                'ordering': ['fecha'],
                'constraints': [models.UniqueConstraint(fields=('jornada', 'local', 'visitante'), name='unique_partido_por_jornada')],
            },
        ),
    ]
