# Generated by Django 6.0.3 on 2026-03-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='penaltis_local',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='penaltis_visitante',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
